name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'ubuntu:20.04'
    steps:
      - uses: actions/checkout@v2
      - name: Install stuff
        run: |
          apt-get update
          TZ=Europe/Minsk
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
          apt-get -y install flex bison build-essential git cmake
      - name: mkdir
        run: mkdir build
      - name: cmake
        run: cd build && cmake .. -DVERIFYPN_Static=ON -DVERIFYPN_MC_Simplification=OFF -DVERIFYPN_TAR=OFF
      - name: make
        run: cd build && make
      - name: Tests
        run: ./run_tests.sh build/bin/verifypn-linux64 "-n" output.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: verifypn-linux64
          path: build/bin/verifypn-linux64
